name: Feature request 💡
description: Suggest an idea for this project.
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Describe the change you'd like
  - type: textarea
    attributes:
      label: Additional context